### ISSUE TITLE
Crash on world loading

### ISSUE THREAD

**Issue by NickDart** [raphydaphy/ArcaneMagic#10]
Hi,

when entering the world i get this error:

java.lang.NoSuchMethodError: net.minecraft.class_332.method_1781(IIFFIIFF)V
	at com.raphydaphy.arcanemagic.client.ClientEvents.drawWandHud(ClientEvents.java:91)
	at com.raphydaphy.arcanemagic.client.ClientEvents.onDrawScreenPost(ClientEvents.java:261)
	at net.minecraft.class_329.handler$worldRenderTick$zfk000(class_329.java:1799)
	at net.minecraft.class_329.method_1753(class_329.java:367)
	at net.minecraft.class_757.method_3192(class_757.java:659)
	at net.minecraft.class_310.method_1523(class_310.java:945)
	at net.minecraft.class_310.method_1514(class_310.java:410)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:347)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

OS:                            Windows 10
Fabric:                        0.3.7.109
Minecraft snapshot:   19w13b.3

Full log here: [log.txt](https://github.com/raphydaphy/ArcaneMagic/files/3026645/log.txt)

Thanks in advance.

**Comment by raphydaphy** [comment]
Thanks for reporting. Unfortunately, the cirseforge release only supports 19w11b for now.
